spring.application.name=final_graduation
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.prefix=classpath:/templates/
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=final_graduation;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa3
spring.datasource.password=1
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Thymeleaf settings
spring.thymeleaf.enabled=true

# Logging settings
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG
#server.servlet.session.timeout=3600


# Server settings
server.port=8080
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,application/json

# Content negotiation
spring.mvc.contentnegotiation.favor-path-extension=false
spring

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
